bcgov/silviculture-ipc

app/src/models/business.js
app/src/routes/v1/ipc.js
app/src/services/dataService.js

name change of function, add a singular getBusiness, and transform db…to api model

data service enhancement

---

app/frontend/src/components/admin/SubmissionsTable.vue

Added confirmation id to the the admin form submissions table
confirmation id is derived from ipcPlanId for now.

added confirmation ID to admin form submissions table

---

app/frontend/src/components/admin/SubmissionsTable.vue
app/src/services/dataService.js

changed table column order and ordered rows by date

changed column order and ordered results by createdAt desc

---

README.md
app/README.md
app/app.js
app/frontend/README.md
openshift/README.md

basic update to readmes to document this project (and not getoken)
The wording will no doubt need some more work..the idea is not to confuse people who are wondering what getok is.

Update readmes (remove getok references)

---

app/src/assets/silvIPC_emailTemplate.html
app/src/components/email.js
app/src/routes/v1/ipc.js
app/tests/unit/components/email.spec.js
app/tests/unit/routes/v1/ipc.spec.js

Issue email after ipc post is received

Add sendReceipt function in email component

---

app/frontend/src/components/form/OrgBookSearch.vue
app/frontend/src/components/form/Step2.vue
app/frontend/src/store/modules/form.js

Making some tweaks with plain control in

Remove org book control temporarily

---

app/frontend/src/components/form/Step1.vue

from the april 22nd requirements update

updated wording, no layout changes

---

app/frontend/src/components/form/Step3.vue

3 certify questions removed included
- guidelinesRead
- assessmentCompleted
- developedPlan
Need to remove them from the database

Updated wording - removed 3 certify questions

---

app/frontend/src/components/form/Step5.vue

new question: infectionAccommodation

step 5 wording - new question added

---

app/frontend/src/components/admin/SubmissionsTable.vue
app/frontend/src/router/index.js
app/frontend/src/services/ipcService.js
app/frontend/src/views/Submission.vue

I've created a new PR for this.
This is the short-term first version I did, showing a single form submission in a simple page.
As our data model is changing and we want to use Lucas's front end form components.. i wont work on this pr much more for now.
I'm not sure if it should be merged.

View Single form submission in Admin panel

---

Jenkinsfile
app/src/components/validators.js
app/tests/fixtures/validIPCPost.json

Allow pipeline to promote to PROD

Add missing boolean field validation

---

app/frontend/src/components/admin/SubmissionsTable.vue
app/frontend/src/services/ipcService.js
app/frontend/src/views/Admin.vue
app/frontend/src/views/Submission.vue
app/src/components/ipcPlanPdf.js

This is the PDF download link on the admin table.
it seems to make the call to CDOGS.
I'll keep working on this.

pdf download link for admin user

---

app/frontend/src/views/Submission.vue

I've added some of the new model/form data to the admin form review page
this probably wont deploy yet. I'll get it working asap.

New data added to the form review page in Admin Panel

---

app/config/custom-environment-variables.json
app/config/test.json
app/src/components/email.js
openshift/README.md

- If the variable isn't defined, no email will dispatch

Add configmap based email recipient functionality

---

app/frontend/src/components/form/Step1.vue
app/src/components/email.js
app/tests/unit/components/email.spec.js

also do not propagate email err

Warning msg on step 1,

---

app/frontend/src/router/index.js
app/frontend/src/views/Dev.vue
app/frontend/tests/unit/views/Dev.spec.js

Move apiTester functionality to /dev subpath

---

app/frontend/src/components/admin/SubmissionsTable.vue
app/frontend/src/components/form/Step6.vue

mobile users and ie having issues downloading submission pdf.
just open the link in another tab/window, do not download file and then createObjectURL.

open pdf url in new tab.

---

app/src/routes/v1/ipc.js
app/src/services/dataService.js
app/src/services/transformService.js

updated dataservice to enforce ordering of status desc.

Add support for ipcPlan status - Create and Read (all).

---

app/src/services/dataService.js

Fix ordering of plan fetch

---

app/frontend/src/components/admin/StatusTable.vue
app/frontend/src/router/index.js
app/frontend/src/services/ipcService.js
app/frontend/src/views/admin/Status.vue
app/frontend/tests/unit/components/admin/StatusTable.spec.js
app/frontend/tests/unit/services/ipcService.spec.js
app/frontend/tests/unit/views/admin/Status.spec.js

To view, login and visit a path with the following pattern:
`/admin/submission/:ipcPlanId/status`

Add StatusTable component support

---

app/config/custom-environment-variables.json
app/config/default.json
app/frontend/src/components/form/CityLookup.vue
app/frontend/src/main.js
openshift/README.md

Just a draft for Lucas to refine and integrate into Step 2.

City Lookup PoC component

---

app/frontend/package.json
app/frontend/src/components/bcgov/BCGovFooter.vue
app/frontend/src/components/form/OrgBookSearch.vue
app/frontend/src/components/form/Step2.vue
app/frontend/src/store/modules/form.js
app/package.json

Leave number of workers blank instead of a default value.
Additional IE11 tweaks.
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)

Don't default 1 for number of workers

---

app/frontend/package-lock.json
app/frontend/vue.config.js
app/package-lock.json
app/src/migrations/20200505203000-5-note-table.js
app/src/models/ipcPlan.js
app/src/models/note.js
app/src/routes/v1/ipc.js
app/src/services/dataService.js
app/src/services/transformService.js

Add notes table and api (protected for inspector role)
Notes can be added to an IPC Plan or an Inspection Status.
New feature (non-breaking change which adds functionality)

Notes table

---

app/frontend/src/components/form/OrgBookSearch.vue

supports: [ticket 1093](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1093)
A warning message if user has entered a business name not found in OrgBook.
New feature (non-breaking change which adds functionality)

show warning if user enters business name not from Org Book

---

app/frontend/src/components/base/BaseDialog.vue
app/frontend/src/components/common/GeneratePdfButton.vue
app/frontend/src/components/form/OrgBookSearch.vue
app/frontend/src/components/form/RequestReceipt.vue
app/frontend/src/components/form/Step6.vue
app/frontend/src/main.js
app/frontend/src/services/emailService.js
app/frontend/tests/unit/services/emailService.spec.js
app/frontend/vue.config.js
app/nodemon.json
app/src/assets/silvIPC_emailTemplate.html
app/src/components/email.js
app/src/components/validators.js
app/src/routes/v1.js
app/src/routes/v1/email.js
app/tests/unit/components/email.spec.js
app/tests/unit/components/validators.spec.js
app/tests/unit/routes/v1/email.spec.js

This PR allows users to email themselves a link to their submitted form results in PDF format. By default, the email field is pre-populated with data they entered in the field as primary contact, but can be changed.
Other Changes:
- Update silvipc email template to use templated link text
- Fix PDF redirection bug on development server
- Remove top-right spinner in loading progress bar animation
- Ignore frontend/node_modules monitoring when using nodemon
- Simplify access to $config object
- Fix double aliased slot in BaseDialog
[SHOWCASE-1074](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1074)
To test, completely fill out the form and submit. On the success page, you should see a new proposed mail button.

Add Email Receipt Request feature for successful submissions

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/components/form/CityLookup.vue
app/frontend/src/components/form/OrgBookSearch.vue
app/package-lock.json
app/package.json

This PR bumps the version to 1.1.1. This is needed as the latitude and longitude fields in the database were recently added which necessitates a different marked version.
New feature (non-breaking change which adds functionality)

Version bump to 1.1.1

---

app/frontend/src/components/admin/SubmissionsTable.vue

add inspection status to admin > submissions table
~~removed 'view' column~~
~~made row clickable.~~
(the two items above had usability implications beyond scope of this ticket)

status and clickable submission table

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/components/form/CityLookup.vue
app/package-lock.json
app/package.json

switched lat and long assignment because i had them the wrong way round.

fixed latitude and longitude miss-match

---

app/frontend/src/components/form/RequestReceipt.vue

This PR fixes the default form refresh behavior.
[SHOWCASE-1156](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1156)
Bug fix (non-breaking change which fixes an issue)

Prevent page refresh on email enter

---

app/frontend/src/components/admin/StatusTable.vue
app/src/services/transformService.js

change date format

---

app/frontend/src/components/admin/SubmissionsTable.vue

Fix IE bug

---

app/frontend/src/components/form/Step1.vue

ticket [1249](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1249)
business notified us that a phone number on the home page was incorrect
Bug fix (non-breaking change which fixes an issue)

updated south area contact phone number on home page

---

app/frontend/src/components/form/Location.vue
app/frontend/src/components/form/Step3.vue

planting fix in title

---

README.md
app/frontend/src/components/bcgov/BCGovHeader.vue

Outage warning and readme deprecation

Outage messages
